### ISSUE TITLE
Plan d'action convergence des dépôts

### ISSUE THREAD

**Issue by jdesboeufs** [sgmap/apicarto#4]
Pour plus de transparence, voici le plan d'action sur lequel on a échangé par email :

__Général__
- [x] Automatisation de l'import des données #1
- [x] Mettre à jour la configuration Ansible pour l'import des données

__Plugin communes__
- [ ] ~~Tests~~
- [x] Import des données #7

__API Quartiers prioritaires__
- [x] Tests #1 
- [x] Documentation #1
- [x] Import des données #1
- [x] Merge dans la branche `master` #1

__API Cadastre IGN__
- [x] Tests #9 
- [x] Documentation sgmap/apicarto-cadastre#11
- [x] Merge dans la branche `master` #9
- [x] Suppression du déploiement `apicarto-cadastre` sur `/cadastre`

__API Appellations viticoles (FranceAgrimer)__
- [x] Merge des derniers patchs #6 
- [x] Tests #22
- [x] Documentation spécifique #17 
- [x] Import des données #7
- [x] Suppression du déploiement `patch-franceagrimer` sur `/aoc`

**Comment by vinsag** [comment]
Je viens de mettre à jour le plan d'action pour la partie documentation qui est en attente de merge sur le dépot apicarto-cadastre suite au pull request: https://github.com/sgmap/apicarto-cadastre/pull/11

**Comment by jdesboeufs** [comment]
Je vais y répondre directement, mais on peut pas encore valider ce point car ce n'est pas consultable par un humain et pas encore sur ce dépôt.
